import{i as c,S as m}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFpSURBVHgBrZQ9UsMwEIXXQoZhcgCobU6RNKlygPTOKUhPDz00UOBbpE9OgX0FD8xQkBAbrYkyirQrK3Fe5bHX79Nqf6JqPG6AUJzN4DLLIETr/B02eU5+kz7z39UK6uIDfBLpnYqdtc8URLLmiwX8PD1CkO7nLET2NlfSsRRE9jXvgshzmPsg0mcu0lQVufCa2jE2ROhuccyTFK6fX1R2fKvi4TBGJImTCXoiROALqhXrsmhTxCAKojPfqBmoy9L9f+dJzoEWDpCZri6cab5mBkzLC6AgAFGweRCAgoSaowQEqmGeuxSUgXnn/1fE756jAVxBQyHyFHOuu1gADpUtfOfrFhOyXS6dWcA1joq+X9+a+IyrAnWl1recTNrDXcy/Ph8iVbh4OgVxcwtbNeJaTVVBl+wY0xwzl2a6eiWculFtc9S+yH0hlPkBoA+EM3cADmQwaLeqT9gtcjhku42cgwPIaARd8u2mP6EkDQvp61kkAAAAAElFTkSuQmCC",i=document.querySelector("form"),p=document.querySelector(".gallery");i.addEventListener("submit",f);function f(o){o.preventDefault();const r=i.elements.search.value;if(r===""){c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Please,enter what do you want to find!"});return}p.innerHTML="",g(r),i.reset()}function g(o){const n=`https://pixabay.com/api/?${new URLSearchParams({key:"42209591-dcd9ad54ecaffcfe9e9b64d04",q:`${o}`,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(n).then(s=>s.json()).then(s=>{const e=s.hits;e.length===0&&h(),y(e),d()})}function h(){c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function d(){let o=new m(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});o.on("show.simpleLightbox"),o.refresh()}function y(o){const r=o.map(({largeImageURL:n,webformatURL:s,tags:e,likes:t,views:a,comments:A,downloads:u})=>`<li class='gallery-item'>
    <a class='gallery-link' href='${n}'>
      <img class='gallery-image' src='${s}' alt='${e}'/>
    </a>
  <div class='container-app'>
  <p><span>Likes</span> ${t}</p>
  <p><span>Views</span> ${a}</p>
  <p><span>Comments</span> ${A}</p>
  <p><span>Downloads</span> ${u}</p>
  </div>
   </li>`).join("");p.innerHTML=r}
//# sourceMappingURL=commonHelpers.js.map
